# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

test:
  tags:
    - hdce_docker
  script:
    - npm ci
    - npm run test
    - npm run test:e2e

deploy:
  tags:
    - hdce_docker
  script:
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'

    ## Run ssh-agent (inside the build environment).
    - eval $(ssh-agent -s)

    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ## Create the SSH directory and give it the right permissions.
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ## Use ssh-keyscan to scan the keys of your private server. Replace gitlab.com
    ## with your own domain name. You can copy and repeat that command if you have
    ## more than one server to connect to.
    - ssh-keyscan 10.131.10.28 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Make sure you have created the pollicam-backend service.
    # Make sure you have executed once the following command: ssh-keyscan -t ed25519 git.list.lu >> ~/.ssh/known_hosts
    - ssh pi@10.131.10.28 "
      sudo systemctl stop pollicam-backend &&
      rm --recursive --force pollicam-backend || true &&
      git clone --single-branch --branch $CI_COMMIT_BRANCH git@git.list.lu:host/mechatronics/pollicam-backend.git &&
      cd pollicam-backend &&
      npm ci &&
      npm run build &&
      cp config/aurinion.env config/production.env &&
      sudo systemctl start pollicam-backend &&
      exit
      "
