# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

image: alpine:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

stages:
  - test
  - analyse
  - build
  - deploy

test:
  image: node:22-alpine
  stage: test
  tags:
    - oceb
  script:
    - npm ci
    - npx prettier --check .
    - npm run test
    - npm run test:e2e

sast:
  stage: analyse
  when: manual
  tags:
    - oceb

include:
  - template: Security/SAST.gitlab-ci.yml

build:
  image: node:22-alpine
  stage: build
  tags:
    - oceb
  script:
    - apk add git
    - npm run build
    - cp config/sample.env config/production.env
  artifacts:
    paths:
      - config/
      - dist/
      - scripts/
      - temp/
      - package.json
      - package-lock.json
      - version.txt

deploy-raspberry-pi:
  stage: deploy
  tags:
    - oceb
  environment:
    name: Raspberry Pi testing
    url: http://$RASPBERRY_PI_HOST
  script:
    ## Install ssh-agent if not already installed, it is required by Docker.
    - 'which ssh-agent || ( apk update && apk add openssh-client )'

    ## Run ssh-agent (inside the build environment).
    - eval $(ssh-agent -s)

    ## Add the SSH key variable to the agent store. We're using tr to fix line
    ## endings which makes ed25519 keys work without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    - echo "$RASPBERRY_PI_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ## Create the SSH directory and give it the right permissions.
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ## Use ssh-keyscan to scan the keys of your private server.
    - ssh-keyscan $RASPBERRY_PI_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Adapt DEVICE_TYPE in config file.
    - sed -i '/^DEVICE_TYPE=/s/=.*/=RaspberryPi/' config/production.env

    # Deploy.
    - ssh $APP4CAM_USER@$RASPBERRY_PI_HOST "
      sudo /root/motion/stop-motion-service.sh &&
      systemctl --user stop $CI_PROJECT_NAME &&
      find $CI_PROJECT_NAME/ -mindepth 1 -maxdepth 1 \! \( -type f -name 'settings.json' \) -exec rm -rf {} + &&
      exit
      "
    - apk add rsync
    - rsync --recursive config dist motion scripts temp package.json package-lock.json version.txt $APP4CAM_USER@$RASPBERRY_PI_HOST:./$CI_PROJECT_NAME
    - ssh $APP4CAM_USER@$RASPBERRY_PI_HOST "
      cd $CI_PROJECT_NAME &&
      npm ci --omit=dev --ignore-scripts &&
      make -C scripts/runtime/raspberry-pi/air-temperature &&
      chmod +x scripts/runtime/raspberry-pi/air-temperature/read_air_temp &&
      chmod g+w motion/config/DiMON/motion.conf &&
      sudo /root/motion/start-motion-service.sh &&
      systemctl --user start $CI_PROJECT_NAME &&
      exit
      "

deploy-variscite-newtcam:
  stage: deploy
  tags:
    - oceb
  environment:
    name: Variscite NEWTCAM testing
    url: http://$VARISCITE_NEWTCAM_HOST
  script:
    ## Install ssh-agent if not already installed, it is required by Docker.
    - 'which ssh-agent || ( apk update && apk add openssh-client )'

    ## Run ssh-agent (inside the build environment).
    - eval $(ssh-agent -s)

    ## Add the SSH key variable to the agent store. We're using tr to fix line
    ## endings which makes ed25519 keys work without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    - echo "$VARISCITE_NEWTCAM_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ## Create the SSH directory and give it the right permissions.
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ## Use ssh-keyscan to scan the keys of your private server.
    - ssh-keyscan $VARISCITE_NEWTCAM_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # Deploy.
    - ssh $APP4CAM_USER@$VARISCITE_NEWTCAM_HOST "
      sudo /root/motion/stop-motion-service.sh &&
      systemctl --user stop $CI_PROJECT_NAME &&
      find $CI_PROJECT_NAME/ -mindepth 1 -maxdepth 1 \! \( -type f -name 'settings.json' \) -exec rm -rf {} + &&
      exit
      "
    - apk add rsync
    - rsync --recursive config dist motion scripts temp package.json package-lock.json version.txt $APP4CAM_USER@$VARISCITE_NEWTCAM_HOST:./$CI_PROJECT_NAME
    - ssh $APP4CAM_USER@$VARISCITE_NEWTCAM_HOST "
      cd $CI_PROJECT_NAME &&
      npm ci --omit=dev --ignore-scripts &&
      make -C scripts/runtime/variscite/battery-monitoring &&
      make -C scripts/runtime/variscite/rtc &&
      make -C scripts/runtime/variscite/wi-fi-control &&
      chmod +x scripts/runtime/variscite/battery-monitoring/battery_monitoring scripts/runtime/variscite/rtc/sleep_until scripts/runtime/variscite/rtc/set_time scripts/runtime/variscite/rtc/get_time scripts/runtime/variscite/wi-fi-control/wifi_control &&
      chmod g+w motion/config/NewtCAM/motion.conf &&
      sudo /root/motion/start-motion-service.sh &&
      systemctl --user start $CI_PROJECT_NAME &&
      exit
      "
